# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Hugo Deploy GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: benmatselby/hugo-deploy-gh-pages@96e9e0e3a9200b291e835de5abc3d7e0d8af6d24
        uses: benmatselby/hugo-deploy-gh-pages@v1.5.0
        with:
          # The version of hugo to use.
          hugo_version: 0.58.3
          # If set to `true`, use the *extended* version of hugo.
          hugo_extended: false # optional
          # Your PAT to authorise the action to do things.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The repo name you want to clone and push to.
          target_repo: varnam
          # If you are defining a custom domain name for your GitHub site, put that value in this variable.
          cname: typeindianlang.online
